var ColorList = [
  {name: "aqua", hex: "#00ffff", groups: "blue, dark", textColor: ""},
  {name: "aliceblue", hex: "#f0f8ff", groups: "blue, light", textColor: ""},
  {name: "antiquewhite", hex: "#faebd7", groups: "white, light", textColor: ""},
  {name: "black", hex: "#000000", groups: "dark", textColor: "#f2f2f2"},
  {name: "blue", hex: "#0000ff", groups: "blue", textColor: "#f2f2f2"},
  {name: "cyan", hex: "#00ffff", groups: "blue", textColor: ""},
  {name: "darkblue", hex: "#00008b", groups: "blue, dark", textColor: "#f2f2f2"},
  {name: "darkcyan", hex: "#008b8b", groups: "green, blue", textColor: ""},
  {name: "darkgreen", hex: "#006400", groups: "green", textColor: "#f2f2f2"},
  {name: "darkturquoise", hex: "#00ced1", groups: "blue, green", textColor: ""},
  {name: "deepskyblue", hex: "#00bfff", groups: "blue", textColor: ""},
  {name: "green", hex: "#008000", groups: "green", textColor: ""},
  {name: "lime", hex: "#00ff00", groups: "green, light", textColor: ""},
  {name: "mediumblue", hex: "#0000cd", groups: "blue", textColor: "#f2f2f2"},
  {name: "mediumspringgreen", hex: "#00fa9a", groups: "flat, green", textColor: ""},
  {name: "navy", hex: "#000080", groups: "blue, dark", textColor: "#f2f2f2"},
  {name: "springgreen", hex: "#00ff7f", groups: "green, light", textColor: ""},
  {name: "teal", hex: "#008080", groups: "dark, green", textColor: ""},
  {name: "midnightblue", hex: "#191970", groups: "blue, dark", textColor: "#f2f2f2"},
  {name: "dodgerblue", hex: "#1e90ff", groups: "blue", textColor: ""},
  {name: "lightseagreen", hex: "#20b2aa", groups: "green", textColor: ""},
  {name: "forestgreen", hex: "#228b22", groups: "green", textColor: ""},
  {name: "seagreen", hex: "#2e8b57", groups: "green, flat", textColor: ""},
  {name: "darkslategray", hex: "#2f4f4f", groups: "dark", textColor: "#f2f2f2"},
  {name: "darkslategrey", hex: "#2f4f4f", groups: "dark", textColor: "#f2f2f2"},
  {name: "limegreen", hex: "#32cd32", groups: "green", textColor: ""},
  {name: "mediumseagreen", hex: "#3cb371", groups: "green", textColor: ""},
  {name: "turquoise", hex: "#40e0d0", groups: "green, blue", textColor: ""},
  {name: "royalblue", hex: "#4169e1", groups: "blue", textColor: ""},
  {name: "steelblue", hex: "#4682b4", groups: "blue, flat", textColor: ""},
  {name: "darkslateblue", hex: "#483d8b", groups: "blue, dark", textColor: "#f2f2f2"},
  {name: "mediumturquoise", hex: "#48d1cc", groups: "green, blue, light", textColor: ""},
  {name: "indigo", hex: "#4b0082", groups: "dark", textColor: "#f2f2f2"},
  {name: "darkolivegreen", hex: "#556b2f", groups: "flat, green", textColor: ""},
  {name: "cadetblue", hex: "#5f9ea0", groups: "flat, blue", textColor: ""},
  {name: "cornflowerblue", hex: "#6495ed", groups: "blue", textColor: ""},
  {name: "mediumaquamarine", hex: "#66cdaa", groups: "green", textColor: ""},
  {name: "dimgray", hex: "#696969", groups: "flat", textColor: ""},
  {name: "dimgrey", hex: "#696969", groups: "flat", textColor: ""},
  {name: "slateblue", hex: "#6a5acd", groups: "", textColor: ""},
  {name: "olivedrab", hex: "#6b8e23", groups: "", textColor: ""},
  {name: "slategray", hex: "#708090", groups: "", textColor: ""},
  {name: "slategrey", hex: "#708090", groups: "", textColor: ""},
  {name: "lightslategray", hex: "#778899", groups: "", textColor: ""},
  {name: "lightslategrey", hex: "#778899", groups: "", textColor: ""},
  {name: "mediumslateblue", hex: "#7b68ee", groups: "", textColor: ""},
  {name: "lawngreen", hex: "#7cfc00", groups: "", textColor: ""},
  {name: "aquamarine", hex: "#7fffd4", groups: "", textColor: ""},
  {name: "chartreuse", hex: "#7fff00", groups: "", textColor: ""},
  {name: "gray", hex: "#808080", groups: "", textColor: ""},
  {name: "grey", hex: "#808080", groups: "", textColor: ""},
  {name: "maroon", hex: "#800000", groups: "", textColor: "#f2f2f2"},
  {name: "olive", hex: "#808000", groups: "", textColor: ""},
  {name: "purple", hex: "#800080", groups: "", textColor: ""},
  {name: "lightskyblue", hex: "#87cefa", groups: "", textColor: ""},
  {name: "skyblue", hex: "#87ceeb", groups: "", textColor: ""},
  {name: "blueviolet", hex: "#8a2be2", groups: "", textColor: ""},
  {name: "darkmagenta", hex: "#8b008b", groups: "", textColor: ""},
  {name: "darkred", hex: "#8b0000", groups: "", textColor: "#f2f2f2"},
  {name: "saddlebrown", hex: "#8b4513", groups: "", textColor: ""},
  {name: "darkseagreen", hex: "#8fbc8f", groups: "", textColor: ""},
  {name: "lightgreen", hex: "#90ee90", groups: "", textColor: ""},
  {name: "mediumpurple", hex: "#9370db", groups: "", textColor: ""},
  {name: "darkviolet", hex: "#9400d3", groups: "", textColor: ""},
  {name: "palegreen", hex: "#98fb98", groups: "", textColor: ""},
  {name: "darkorchid", hex: "#9932cc", groups: "", textColor: ""},
  {name: "yellowgreen", hex: "#9acd32", groups: "", textColor: ""},
  {name: "sienna", hex: "#a0522d", groups: "", textColor: ""},
  {name: "brown", hex: "#a52a2a", groups: "", textColor: ""},
  {name: "darkgray", hex: "#a9a9a9", groups: "", textColor: ""},
  {name: "darkgrey", hex: "#a9a9a9", groups: "", textColor: ""},
  {name: "greenyellow", hex: "#adff2f", groups: "", textColor: ""},
  {name: "lightblue", hex: "#add8e6", groups: "", textColor: ""},
  {name: "paleturquoise", hex: "#afeeee", groups: "", textColor: ""},
  {name: "lightsteelblue", hex: "#b0c4de", groups: "", textColor: ""},
  {name: "powderblue", hex: "#b0e0e6", groups: "", textColor: ""},
  {name: "firebrick", hex: "#b22222", groups: "", textColor: ""},
  {name: "darkgoldenrod", hex: "#b8860b", groups: "", textColor: ""},
  {name: "mediumorchid", hex: "#ba55d3", groups: "", textColor: ""},
  {name: "rosybrown", hex: "#bc8f8f", groups: "", textColor: ""},
  {name: "darkkhaki", hex: "#bdb76b", groups: "", textColor: ""},
  {name: "silver", hex: "#c0c0c0", groups: "", textColor: ""},
  {name: "mediumvioletred", hex: "#c71585", groups: "", textColor: ""},
  {name: "indianred", hex: "#cd5c5c", groups: "", textColor: ""},
  {name: "peru", hex: "#cd853f", groups: "", textColor: ""},
  {name: "chocolate", hex: "#d2691e", groups: "", textColor: ""},
  {name: "tan", hex: "#d2b48c", groups: "", textColor: ""},
  {name: "lightgray", hex: "#d3d3d3", groups: "", textColor: ""},
  {name: "lightgrey", hex: "#d3d3d3", groups: "", textColor: ""},
  {name: "thistle", hex: "#d8bfd8", groups: "", textColor: ""},
  {name: "goldenrod", hex: "#daa520", groups: "yellow", textColor: ""},
  {name: "orchid", hex: "#da70d6", groups: "", textColor: ""},
  {name: "palevioletred", hex: "#db7093", groups: "", textColor: ""},
  {name: "crimson", hex: "#dc143c", groups: "red", textColor: ""},
  {name: "gainsboro", hex: "#dcdcdc", groups: "light", textColor: ""},
  {name: "plum", hex: "#dda0dd", groups: "", textColor: ""},
  {name: "burlywood", hex: "#deb887", groups: "", textColor: ""},
  {name: "lightcyan", hex: "#e0ffff", groups: "", textColor: ""},
  {name: "lavender", hex: "#e6e6fa", groups: "", textColor: ""},
  {name: "darksalmon", hex: "#e9967a", groups: "red, flat, yellow", textColor: ""},
  {name: "palegoldenrod", hex: "#eee8aa", groups: "yellow", textColor: ""},
  {name: "violet", hex: "#ee82ee", groups: "", textColor: ""},
  {name: "azure", hex: "#f0ffff", groups: "", textColor: ""},
  {name: "honeydew", hex: "#f0fff0", groups: "", textColor: ""},
  {name: "khaki", hex: "#f0e68c", groups: "yellow, flat", textColor: ""},
  {name: "lightcoral", hex: "#f08080", groups: "", textColor: ""},
  {name: "sandybrown", hex: "#f4a460", groups: "", textColor: ""},
  {name: "beige", hex: "#f5f5dc", groups: "", textColor: ""},
  {name: "mintcream", hex: "#f5fffa", groups: "", textColor: ""},
  {name: "wheat", hex: "#f5deb3", groups: "", textColor: ""},
  {name: "whitesmoke", hex: "#f5f5f5", groups: "light", textColor: ""},
  {name: "ghostwhite", hex: "#f8f8ff", groups: "light", textColor: ""},
  {name: "lightgoldenrodyellow", hex: "#fafad2", groups: "", textColor: ""},
  {name: "linen", hex: "#faf0e6", groups: "", textColor: ""},
  {name: "salmon", hex: "#fa8072", groups: "", textColor: ""},
  {name: "oldlace", hex: "#fdf5e6", groups: "", textColor: ""},
  {name: "bisque", hex: "#ffe4c4", groups: "yellow, red", textColor: ""},
  {name: "blanchedalmond", hex: "#ffebcd", groups: "", textColor: ""},
  {name: "coral", hex: "#ff7f50", groups: "red, flat", textColor: ""},
  {name: "cornsilk", hex: "#fff8dc", groups: "", textColor: ""},
  {name: "darkorange", hex: "#ff8c00", groups: "yellow, red", textColor: ""},
  {name: "deeppink", hex: "#ff1493", groups: "", textColor: ""},
  {name: "floralwhite", hex: "#fffaf0", groups: "", textColor: ""},
  {name: "fuchsia", hex: "#ff00ff", groups: "", textColor: ""},
  {name: "gold", hex: "#ffd700", groups: "yellow", textColor: ""},
  {name: "hotpink", hex: "#ff69b4", groups: "", textColor: ""},
  {name: "ivory", hex: "#fffff0", groups: "", textColor: ""},
  {name: "lavenderblush", hex: "#fff0f5", groups: "", textColor: ""},
  {name: "lemonchiffon", hex: "#fffacd", groups: "", textColor: ""},
  {name: "lightpink", hex: "#ffb6c1", groups: "", textColor: ""},
  {name: "lightsalmon", hex: "#ffa07a", groups: "", textColor: ""},
  {name: "lightyellow", hex: "#ffffe0", groups: "", textColor: ""},
  {name: "magenta", hex: "#ff00ff", groups: "flat", textColor: ""},
  {name: "mistyrose", hex: "#ffe4e1", groups: "", textColor: ""},
  {name: "moccasin", hex: "#ffe4b5", groups: "", textColor: ""},
  {name: "navajowhite", hex: "#ffdead", groups: "red, light", textColor: ""},
  {name: "orange", hex: "#ffa500", groups: "red", textColor: ""},
  {name: "orangered", hex: "#ff4500", groups: "red, flat", textColor: ""},
  {name: "papayawhip", hex: "#ffefd5", groups: "light, flat", textColor: ""},
  {name: "peachpuff", hex: "#ffdab9", groups: "light, flat", textColor: ""},
  {name: "pink", hex: "#ffc0cb", groups: "red, flat", textColor: ""},
  {name: "red", hex: "#ff0000", groups: "red", textColor: ""},
  {name: "seashell", hex: "#fff5ee", groups: "light, yellow", textColor: ""},
  {name: "snow", hex: "#fffafa", groups: "light", textColor: ""},
  {name: "tomato", hex: "#ff6347", groups: "red, flat", textColor: ""},
  {name: "white", hex: "#ffffff", groups: "light", textColor: ""},
  {name: "yellow", hex: "#ffff00", groups: "yellow", textColor: ""},
  {name: "rebeccapurple", hex: "#663399", groups: "", textColor: "#f2f2f2"}
];

module.exports = ColorList;